#pragma once

#define PLOOPY_DRAGSCROLL_SCRLK_ENABLE
#define PLOOPY_VIAMENUS
#define BETTER_DRAGSCROLL
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 26
#define PLOOPY_MSGESTURE_ENABLE

#define BETTER_DRAGSCROLL_INVERT_V 1
#define BETTER_DRAGSCROLL_DIVISOR_V 8
#define BETTER_DRAGSCROLL_DIVISOR_H 8
