#pragma once

#define PLOOPY_VIAMENUS
#define BETTER_DRAGSCROLL
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 14
#define PLOOPY_MSGESTURE_ENABLE
#define BETTER_DRAGSCROLL_TAPDANCE

#define BETTER_DRAGSCROLL_DIVISOR_H 8
#define BETTER_DRAGSCROLL_DIVISOR_V 8
